### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by yulei666** [hhru/nginx_requestid#2]
Reading and writing beyond the bounds of the array hashb and hasht

u_char						   hasht[MD5_HASH_LEN];
    for (i = 0; i < MD5_HASH_LEN; i++) {
		*p++ = hex[hashb[i] >> 4];
		*p++ = hex[hashb[i] & 0xf];
    }
    *p = 0;

should be

u_char						   hasht[MD5_HASH_LEN + 1];
    for (i = 0; i < MD5_BHASH_LEN; i++) {
		*p++ = hex[hashb[i] >> 4];
		*p++ = hex[hashb[i] & 0xf];
    }
    *p = 0;

**Comment by selim-mustafaev** [comment]
New code, but old bugs... 
Code on line #113:

    hasht[i+1] = hex[hashb[k] & 0xf];

writes out of array bounds (on last iteration), which leads to infinite loop (at least on GCC 4.8)
temporary solution - change line #106 from this:

    u_char hasht[MD5_HASH_LEN];

to this:

    u_char hasht[MD5_HASH_LEN + 1];

**Comment by Aulust** [comment]
This issue should be fixed by @7cc6008b14190481078c2e1ea5baa726bd6680db . In case of bugs in current code please open a new issue.
