### ISSUE TITLE
Availability on Windows

### ISSUE THREAD

**Issue by TwentyOneSolutions** [hhru/nginx_requestid#7]
Is this available on Windows?

I installed nginx 1.11.2 and the changelog shows that this was added in 1.11.0: https://nginx.org/en/CHANGES

    Changes with nginx 1.11.0                                        24 May 2016

    *) Feature: the $request_id variable.

But when I try to start nginx with `requestid on;` I get an error:

> nginx: [emerg] unknown directive "requestid"

**Comment by TwentyOneSolutions** [comment]
Or is it always on by default and only the directive as specified in `README` is "bad"?  I see that I can do 

    add_header  X-Request-Id    $request_id;

And it works.

**Comment by Aulust** [comment]
This module has nothing to do with $request_id variable now available in nginx (apart from sharing a same variable name by a coincidence).

This module might be useful with older versions of nginx or if you need to have timestamp prefix for request id. In your case it's better to use $request_id from 1.11.0 without compiling this module.

**Comment by TwentyOneSolutions** [comment]
Oh, thank you for clarifying.  The first few results on google for `nginx request_id` bring up this page and I couldn't find anything else that made sense so I thought that this was the base for `$request_id`.
